# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

alias ll="ls -alhFo --group-directories-first --time-style=long-iso --color=auto"
alias regenLock="rm node_modules/ -rf && rm package-lock.json && npm cache clear --force && npm i && npm audit fix"
